```{r}
library(MASS)
library(dplyr)
library(FNN)
```

```{r}
BostonStd <- Boston %>%
  mutate(age.std = scale(Boston[,"age"]),
         rad.std = scale(Boston[,"rad"])) %>%
  dplyr::select(age, rad, age.std, rad.std, crim)
```

```{r}
x.std <- BostonStd %>%
  dplyr::select(age.std, rad.std)

y <- BostonStd$crim
```

```{r}
prediction = knn.reg(train = x.std,
                     test = x.std,
                     y = y,
                     k = 25)

mean((y - prediction$pred)^2)
```
```{r}
BostonStd <- Boston %>%
  mutate(age.std = scale(Boston[,"age"]),
         rad.std = scale(Boston[,"rad"])) %>%
  dplyr::select(age, rad, age.std, rad.std, crim)

Model = lm(crim ~ age.std + rad.std, data = BostonStd)
```

```{r}
# LOOCV
nfolds=dim(BostonStd)[1]
cvgroups = (1:nfolds)
############# CV process for one of the models #############

allpredicted = rep(NA,n)   # storage for honest predictions

# loop to do cross-validation

 for (ii in 1: nfolds) {    # ii is an easier string to search for index
   groupii = (cvgroups == ii)     # logical vector for group ii
   trainset = BostonStd[!groupii,]  # all data EXCEPT for group ii
   testset = BostonStd[groupii, ]   # data in group ii
   
   modelfit = lm(Model, data=trainset) # fit to train set
   
   predicted = predict(modelfit, newdata = testset)   # predict for test set
   allpredicted[groupii] = predicted              # store in ordered locations
 }


```

```{r}
### WeBWork #2
### Answer from WeBWork
x <- BostonStd %>% 
  dplyr::select(age,rad)
n=dim(BostonStd)[1]
LOOCVpredictions = rep(NA,n)

cvgroups = 1:n
nfolds=n
for (ii in 1: nfolds) {    # ii is an easier string to search for index
  groupii = (cvgroups == ii)     # logical vector for group ii
  train.x = x[!groupii,]
  train.x.std = scale(train.x) # scale set in loop
  train.y = y[!groupii]
  test.x = x[groupii,]
  test.x.std = scale(test.x, 
                     center = attr(train.x.std, "scaled:center"), 
                     scale = attr(train.x.std, "scaled:scale"))
  predictions = knn.reg(train.x.std, test.x.std, train.y, k = 25) # run the model
  LOOCVpredictions[groupii] = predictions$pred
}
mean( (y - LOOCVpredictions)^2 )
```

```{r}
### Code from Piazza
library(FNN)
library(MASS)

kneighbor = 25

n = dim(Boston)[1]
nfolds = 10

set.seed(2)

groups = rep(1:nfolds,length=n)

cvgroups = sample(groups,n)

preditors <- Boston[c('age', 'rad')]
response <- Boston$crim

allpredicted = rep(NA,n)

for (ii in 1: nfolds) {

groupii = (cvgroups == ii)

preditors.trainset = preditors[!groupii,]
response.trainset = response[!groupii]

preditors.testset = preditors[groupii,]

preditors.trainset.std <- scale(preditors.trainset)
preditors.testset.std <- scale(preditors.testset,
center = attr(preditors.trainset.std , "scaled:center"),
scale = attr(preditors.trainset.std , "scaled:scale"))

predicted = knn.reg(train = preditors.trainset.std,
test = preditors.testset.std,
y = response.trainset,
 k = kneighbor)

# store the regression prediction values
allpredicted[groupii] = predicted$pred
}

CVValue = mean((response - allpredicted)^2)
CVValue
```
```{r}
### WeBWork #3
### Answer from WeBWork
tenfoldCVpredictions = rep(NA,n)
for (ii in 1: nfolds) {    # ii is an easier string to search for index
  groupii = (cvgroups == ii)     # logical vector for group ii
  train.x = x[!groupii,]
  train.x.std = scale(train.x)
  train.y = y[!groupii]
  test.x = x[groupii,]
  test.x.std = scale(test.x, 
                     center = attr(train.x.std, "scaled:center"), 
                     scale = attr(train.x.std, "scaled:scale"))
  predictions = knn.reg(train.x.std, test.x.std, train.y, k = 25)
  tenfoldCVpredictions[groupii] = predictions$pred
}
mean( (y - tenfoldCVpredictions)^2 )
```

```{r}
### WeBWork #5
Model1 = lm(crim ~ rad, data = Boston)
Model2 = lm(crim ~ rad + age, data = Boston)
Model3 = lm(crim ~ ., data = Boston)


ModelUsed = Model3

BostonStd <- Boston %>%
  mutate(age.std = scale(Boston[,"age"]),
         rad.std = scale(Boston[,"rad"])) %>%
  dplyr::select(age, rad, age.std, rad.std, crim)

x <- BostonStd %>% 
  dplyr::select(age,rad)

nfolds=10; n = dim(Boston)[1]
groups = rep(1:nfolds,length=n)
set.seed(2)
cvgroups = sample(groups,n)

### Answer from WeBWork

tenfoldCVpredictions = rep(NA,n)
for (ii in 1:nfolds) {    # ii is an easier string to search for index
  groupii = (cvgroups == ii)     # logical vector for group ii
  trainset = Boston[!groupii,]  # all data EXCEPT for group ii
  testset = Boston[groupii, ]   # data in group ii
  modelfit = lm(ModelUsed, data=trainset) # fit to train set
  predicted = predict(modelfit, newdata = testset)   # predict for test set
  tenfoldCVpredictions[groupii] = predicted
}
mean( (y - tenfoldCVpredictions)^2 )
```

```{r}
BostonT <- Boston %>% 
  mutate(log.crim = log(crim)) %>% 
  dplyr::select(age,rad,log.crim)
```

```{r}
lmfit = lm(log.crim ~ ., data = BostonT)
summary(lmfit)  # see column Std. Error
```

```{r}
beta.fn = function(inputdata,index) {
  lmfitboot = lm(formula = log.crim ~., data= inputdata[index,])
  return(lmfitboot$coef)
} 
beta.fn(BostonT,1:n)  # outputs coefficients of model fit on full dataset (observations 1 to n)
```

```{r}
library(boot)
set.seed(2)
bootoutput = boot(BostonT,beta.fn,R=5000)
print(bootoutput)
# standard error as estimated via simulation
round(sd((bootoutput$t)[,1]),6); hist((bootoutput$t)[,1])

round(sd((bootoutput$t)[,2]),6); hist((bootoutput$t)[,2])

round(sd((bootoutput$t)[,3]),6); hist((bootoutput$t)[,3])
```

